Create project folder for inheritance and access modifiers theme + README file
bodacd/automation-study-materials pull request #10
Opened 2024-01-29 13:30 UTC by olga-vozian

Description of inheritance and access modifiers with example

2024-01-29 13:53 UTC, anamalaiaEndava commented on JT/10 inheritance and access modifiers/Example/Access Modifiers/README_ACCESS_MODIFIERS.md
> +![Access Modifiers.png](C:\Projects\bench\automation-study-materials\JT\11 inheritance and access modifiers\resources\Access Modifiers\Access_Modifiers.png)
This image didn't load for me, check it please?

2024-01-30 08:03 UTC, tascaV requested changes
Please use JavaDoc for all Java files (tutorial -> https://www.baeldung.com/javadoc). 
For start it will be enough to comment all non-syntax text in classes. Thank you.

2024-01-30 09:21 UTC, tascaV approved these changes

2024-01-30 10:15 UTC, AlexProdanov approved these changes

2024-01-30 10:16 UTC, merged