added description about assertions, matchers, custom assertions
bodacd/automation-study-materials pull request #28
Opened 2024-02-28 15:05 UTC by IlGrecu

Added info about assertions/matchers:

- Assertions. General overview
- Hard assertions - Junit
- Matchers - Hamcrest
- Soft assertions - assertj
- Custom assertions

2024-02-29 08:23 UTC, endalexei commented on TL/21_assertions_matchers_custom_assertions/Assertions_Matchers_CustomAssertions_README.md
> +2. [Hard assertions - Junit](#hard-assertions-junit)
please make sure links work as expected

2024-02-29 08:24 UTC, endalexei commented on TL/21_assertions_matchers_custom_assertions/Assertions_Matchers_CustomAssertions_README.md
> +![img.png](resources/assertion representation.png)
this image wont open for me

2024-02-29 08:28 UTC, endalexei commented on TL/21_assertions_matchers_custom_assertions/Assertions_Matchers_CustomAssertions_README.md
> +![img.png](resources/multiple hard assert failed scenarios.png)
this image is not loaded for me

2024-02-29 08:29 UTC, endalexei commented on TL/21_assertions_matchers_custom_assertions/Assertions_Matchers_CustomAssertions_README.md
> +![img.png](resources/soft assert failed scenarios.png)
please check that images are seen

2024-02-29 08:30 UTC, endalexei requested changes
Nice job, most of the projects require I commit per PR, would you like to try and swash this 2 commits you have ?

2024-02-29 14:19 UTC, rudenco commented
Liked the clarity and diversity of explanations + the diversity of libraries used besides JUnit. 
Good examples with Streams and Lamdbas usage in tests.

2024-03-12 07:27 UTC, bodacd approved these changes

2024-03-13 13:53 UTC, endalexei approved these changes

2024-03-14 12:30 UTC, merged