Create project initial folders for33_api_requests_in_cucumber_tests theme + README files
bodacd/automation-study-materials pull request #6
Opened 2024-01-24 10:07 UTC by diogotia

initial commit 
1) Introducing new module andreidiogoti_33_api_requests_in_cucumber_tests
2) Creating base project structure :1.
1. Folder with project under test 'src/main/java/org/apitests'
2. API testing framework 'src/test/java/org/apitests'
3. Readme files with  detailed descriptions

2024-01-24 10:31 UTC, diogotia commented
It is Draft PR - Work in progress.

2024-01-24 10:33 UTC, endalexei commented
please remove toBeDeleted.file as it was temporary added to be able to create folders

2024-01-24 10:34 UTC, endalexei commented
why do we need the _index file ?

2024-01-24 10:36 UTC, endalexei commented on ST/32_api_requests_in_cucumber_tests/docs/cucumber.md
> +{{% text "java" %}}Depending on the table shape as one of the following collections:{{% /text %}}
this {{% text "java" %}} appears on  page, is it intended ?
<img width="738" alt="image" src="https://github.com/bodacd/automation-study-materials/assets/5145950/abe7de3b-d12e-4456-8b63-8f71653d857c">

2024-01-24 12:10 UTC, diogotia commented
> please remove toBeDeleted.file as it was temporary added to be able to create folders

toBeDeleted.file deleted

2024-01-24 12:16 UTC, diogotia commented
> why do we need the _index file ? it useless here. Was deleted

2024-01-29 10:02 UTC, tascaV commented on ST/32_api_requests_in_cucumber_tests/docs/api-tests-with-cumber.md
> +This is a project used for increase technical skills on API requests in Cucumber tests
Remove line, not required

2024-01-29 10:03 UTC, tascaV commented on ST/32_api_requests_in_cucumber_tests/docs/api-tests-with-cumber.md
> +1. [1. Project overview](#1-project-overview)
remove redundant list:
[1.
[2.
[3.

2024-01-29 10:04 UTC, tascaV commented on ST/32_api_requests_in_cucumber_tests/docs/api-tests-with-cumber.md
> +1. Folder with project under test 'src/main/java/org/apitests'
~Folder with project under test~ -> Service under test

2024-01-29 10:07 UTC, tascaV commented on ST/32_api_requests_in_cucumber_tests/docs/api-tests-with-cumber.md
> +1. **Java Cucumber BDD framework**
Cucumber

2024-01-29 10:07 UTC, tascaV commented on ST/32_api_requests_in_cucumber_tests/docs/api-tests-with-cumber.md
> +2. **RestFull API**
REST Assured

2024-01-29 10:45 UTC, tascaV commented on ST/32_api_requests_in_cucumber_tests/docs/framework_setup.md
> +## Setup RestAssured API Tests using the Cucumber BDD Style Test
L31-L33 can be removed

2024-01-29 11:18 UTC, tascaV requested changes
Please redo the documentation using snippets of code from example test framework. As well I will suggest to remove example test framework.
So to sum it up: embed source code within documentation itself.

2024-01-30 12:44 UTC, diogotia commented on ST/32_api_requests_in_cucumber_tests/docs/api-tests-with-cumber.md
> +1. **Java Cucumber BDD framework**
Updated

2024-01-30 13:16 UTC, diogotia commented on ST/32_api_requests_in_cucumber_tests/docs/api-tests-with-cumber.md
> +3. **JUnit test runner**
Updated

2024-01-30 13:16 UTC, diogotia commented on ST/32_api_requests_in_cucumber_tests/docs/api-tests-with-cumber.md
> +2. **RestFull API**
updated on REST Assured

2024-01-30 13:16 UTC, diogotia commented on ST/32_api_requests_in_cucumber_tests/docs/api-tests-with-cumber.md
> +1. Folder with project under test 'src/main/java/org/apitests'
updated

2024-01-30 13:16 UTC, diogotia commented on ST/32_api_requests_in_cucumber_tests/docs/api-tests-with-cumber.md
> +1. [1. Project overview](#1-project-overview)
updated

2024-01-30 13:16 UTC, diogotia commented on ST/32_api_requests_in_cucumber_tests/docs/api-tests-with-cumber.md
> +This is a project used for increase technical skills on API requests in Cucumber tests
Removed

2024-01-31 14:02 UTC, tascaV reviewed
Looks good. Add some step defs examples and good to be merged

2024-02-01 09:41 UTC, bodacd approved these changes

2024-02-01 10:47 UTC, diogotia commented
Step definition and Runner examples added

2024-02-02 11:33 UTC, tascaV approved these changes

2024-02-02 11:33 UTC, rusakoviurii-Endava approved these changes

2024-02-02 11:35 UTC, olga-vozian approved these changes

2024-02-02 11:42 UTC, merged